//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArnetAdminApp.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agent
    {
        public int Id { get; set; }
        public int AgencyId { get; set; }
        public int UserId { get; set; }
        public Nullable<System.DateTime> DateTo { get; set; }
        public System.DateTime DateFrom { get; set; }
    
        public virtual User User { get; set; }
        public virtual Agency Agency { get; set; }
    }
}
